server:
    port: 8081
    
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle    
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  type-aliases-package: com.example.docker_spring.vo
  mapper-locations: classpath:mapper/*.xml